/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ecoreverse.visao;

/**
 *
 * @author Miguel
 */
public class TelaTriagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaTriagem
     */
    public TelaTriagem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblTelaDeTriagem = new javax.swing.JLabel();
        LblIDEquipamento = new javax.swing.JLabel();
        LblData = new javax.swing.JLabel();
        LblLaudo = new javax.swing.JLabel();
        LblMarca3 = new javax.swing.JLabel();
        TxtID_Equipamento = new javax.swing.JTextField();
        TxtData = new javax.swing.JTextField();
        TxtLaudo = new javax.swing.JTextField();
        TxtPecas_Substituidas = new javax.swing.JTextField();
        BtnSalvarLaudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblTelaDeTriagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTelaDeTriagem.setText("TELA DE TRIAGEM");

        LblIDEquipamento.setText("ID_Equipamento");

        LblData.setText("Data");

        LblLaudo.setText("Laudo");

        LblMarca3.setText("Peças_Substituidas");

        TxtID_Equipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtID_EquipamentoActionPerformed(evt);
            }
        });

        TxtData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDataActionPerformed(evt);
            }
        });

        TxtLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtLaudoActionPerformed(evt);
            }
        });

        TxtPecas_Substituidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPecas_SubstituidasActionPerformed(evt);
            }
        });

        BtnSalvarLaudo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BtnSalvarLaudo.setText("Salvar Laudo");
        BtnSalvarLaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarLaudoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblTelaDeTriagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblMarca3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtPecas_Substituidas))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblIDEquipamento)
                            .addComponent(LblData))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtData)
                            .addComponent(TxtID_Equipamento)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblLaudo)
                        .addGap(72, 72, 72)
                        .addComponent(TxtLaudo)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalvarLaudo)
                .addGap(112, 112, 112))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblTelaDeTriagem)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblIDEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtID_Equipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblData, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtPecas_Substituidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(BtnSalvarLaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDataActionPerformed

    private void TxtPecas_SubstituidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPecas_SubstituidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPecas_SubstituidasActionPerformed

    private void TxtLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtLaudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtLaudoActionPerformed

    private void TxtID_EquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtID_EquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtID_EquipamentoActionPerformed

    private void BtnSalvarLaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarLaudoActionPerformed
try {
            com.mycompany.ecoreverse.modelo.Triagem triagem = new com.mycompany.ecoreverse.modelo.Triagem();
            
            // Converte o texto da tela para número inteiro
            triagem.setEquipamentoId(Integer.parseInt(TxtID_Equipamento.getText()));
            triagem.setDataTeste(TxtData.getText());
            triagem.setLaudoTecnico(TxtLaudo.getText());
            triagem.setComponentesSubstituidos(TxtPecas_Substituidas.getText());

            com.mycompany.ecoreverse.dao.TriagemDAO dao = new com.mycompany.ecoreverse.dao.TriagemDAO();

            if (dao.registrarLaudo(triagem)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Laudo salvo e status atualizado com sucesso!");
                // Limpa os campos
                TxtID_Equipamento.setText("");
                TxtData.setText("");
                TxtLaudo.setText("");
                TxtPecas_Substituidas.setText("");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao salvar laudo no banco.");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite apenas números no campo ID do Equipamento.");
        }
    }//GEN-LAST:event_BtnSalvarLaudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTriagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTriagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvarLaudo;
    private javax.swing.JLabel LblData;
    private javax.swing.JLabel LblIDEquipamento;
    private javax.swing.JLabel LblLaudo;
    private javax.swing.JLabel LblMarca3;
    private javax.swing.JLabel LblTelaDeTriagem;
    private javax.swing.JTextField TxtData;
    private javax.swing.JTextField TxtID_Equipamento;
    private javax.swing.JTextField TxtLaudo;
    private javax.swing.JTextField TxtPecas_Substituidas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
